literals <- read.csv('/ifi/bifrost/a03/kjekje/data/literals-excerpt2.csv')
framelit <- as.data.frame(table(literals))
framelit$length <- sapply(levels(framelit$literals), nchar)
plot(framelit$length, framelit$Freq, log="xy")
litlm <- lm(framelit$Freq ~ framelit$length)
